"""crear tabla app_usage y blocked_ app

Revision ID: 12b3206dea6d
Revises: 8df05d2caf73
Create Date: 2025-11-09 20:11:43.755310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b3206dea6d'
down_revision: Union[str, Sequence[str], None] = '8df05d2caf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('limited_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_apps_id'), 'blocked_apps', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_apps_user_id'), 'blocked_apps', ['user_id'], unique=False)
    op.create_table('app_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app_name', 'date', name='_user_app_date_uc')
    )
    op.create_index(op.f('ix_app_usages_id'), 'app_usages', ['id'], unique=False)
    op.create_index(op.f('ix_app_usages_user_id'), 'app_usages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_usages_user_id'), table_name='app_usages')
    op.drop_index(op.f('ix_app_usages_id'), table_name='app_usages')
    op.drop_table('app_usages')
    op.drop_index(op.f('ix_blocked_apps_user_id'), table_name='blocked_apps')
    op.drop_index(op.f('ix_blocked_apps_id'), table_name='blocked_apps')
    op.drop_table('blocked_apps')
    # ### end Alembic commands ###
